-- ============================================================================
-- NINJA Digital — Client Portal Schema
-- Run this in Supabase SQL editor on a fresh project.
-- Includes Row Level Security (RLS) so each client sees only their own data.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. Tables
-- ----------------------------------------------------------------------------

-- Clients = Google Ads accounts under Sharon's MCC
create table public.clients (
  id uuid primary key default gen_random_uuid(),
  google_ads_customer_id text unique,         -- e.g. "1230389197"
  business_name text not null,
  vertical text,                              -- "service" | "ecom" | other
  currency_code text default 'USD',           -- 'USD' | 'ILS' | 'EUR' | 'GBP' | ...
  primary_contact_email text,
  status text default 'active',               -- 'active' | 'paused' | 'archived'
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Admin users (Sharon + any team)
create table public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  added_at timestamptz default now()
);

-- Client users (one or many people per client business who can log in)
create table public.client_users (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  client_id uuid not null references public.clients(id) on delete cascade,
  role text default 'viewer',                 -- 'viewer' | 'admin' (client-side admin)
  added_at timestamptz default now(),
  unique(user_id, client_id)
);

-- Strategy doc per client (versioned via updated_at)
create table public.strategies (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references public.clients(id) on delete cascade,
  title text not null,
  content_md text not null,
  version int default 1,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Reports (Markdown content, generated by Sharon's skills + uploaded)
create table public.reports (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references public.clients(id) on delete cascade,
  type text not null,                         -- weekly | health | diagnose | out_of_area | settings_audit | n_gram | ...
  report_date date not null,                  -- the period the report covers
  title text not null,
  content_md text not null,
  generated_at timestamptz default now(),
  visible_to_client boolean default false     -- Sharon's manual gate before publishing
);

-- Change log: timeline of actions Sharon took on the campaigns
create table public.change_log (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references public.clients(id) on delete cascade,
  occurred_at timestamptz default now(),
  category text not null,                     -- 'budget' | 'bidding' | 'keywords' | 'ads' | 'audience' | 'other'
  description text not null,                  -- short human-readable summary
  details_md text,                            -- optional longer note
  by_user uuid references auth.users(id),
  visible_to_client boolean default true
);

-- Search-term snapshots (n-gram analysis output)
create table public.search_terms_snapshot (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references public.clients(id) on delete cascade,
  snapshot_date date not null,
  top_ngrams jsonb,                           -- [{ngram, cost, clicks, conv, n}, ...]
  recommended_negatives jsonb,                -- [{text, match_type}, ...]
  created_at timestamptz default now()
);

-- KPI snapshots (daily, for charts and WoW deltas)
create table public.kpi_snapshots (
  client_id uuid not null references public.clients(id) on delete cascade,
  date date not null,
  clicks int default 0,
  impressions int default 0,
  conversions numeric(10,2) default 0,
  conversions_value numeric(12,2) default 0,
  cost numeric(12,2) default 0,
  primary key (client_id, date)
);

-- Indexes for common queries
create index reports_client_date_idx on public.reports (client_id, report_date desc);
create index change_log_client_idx on public.change_log (client_id, occurred_at desc);
create index search_terms_client_idx on public.search_terms_snapshot (client_id, snapshot_date desc);

-- ----------------------------------------------------------------------------
-- 2. Helper function: is the calling user an admin?
-- ----------------------------------------------------------------------------
create or replace function public.is_admin()
returns boolean
language sql
security definer
stable
as $$
  select exists(select 1 from public.admin_users where user_id = auth.uid());
$$;

-- ----------------------------------------------------------------------------
-- 3. Row Level Security (RLS)
-- Each client sees only their own data. Admins see everything.
-- ----------------------------------------------------------------------------

alter table public.clients enable row level security;
alter table public.admin_users enable row level security;
alter table public.client_users enable row level security;
alter table public.strategies enable row level security;
alter table public.reports enable row level security;
alter table public.change_log enable row level security;
alter table public.search_terms_snapshot enable row level security;
alter table public.kpi_snapshots enable row level security;

-- Admins see all; clients see only their own
create policy clients_select on public.clients for select
  using (public.is_admin() or id in (select client_id from public.client_users where user_id = auth.uid()));

create policy admin_users_select on public.admin_users for select
  using (auth.uid() = user_id or public.is_admin());

create policy client_users_select on public.client_users for select
  using (public.is_admin() or user_id = auth.uid());

create policy strategies_select on public.strategies for select
  using (public.is_admin() or client_id in (select client_id from public.client_users where user_id = auth.uid()));

create policy reports_select on public.reports for select
  using (
    public.is_admin()
    or (visible_to_client = true and client_id in (select client_id from public.client_users where user_id = auth.uid()))
  );

create policy change_log_select on public.change_log for select
  using (
    public.is_admin()
    or (visible_to_client = true and client_id in (select client_id from public.client_users where user_id = auth.uid()))
  );

create policy search_terms_select on public.search_terms_snapshot for select
  using (public.is_admin() or client_id in (select client_id from public.client_users where user_id = auth.uid()));

create policy kpi_select on public.kpi_snapshots for select
  using (public.is_admin() or client_id in (select client_id from public.client_users where user_id = auth.uid()));

-- WRITE policies — only admins (Sharon) can mutate
create policy clients_admin_write on public.clients for all using (public.is_admin()) with check (public.is_admin());
create policy strategies_admin_write on public.strategies for all using (public.is_admin()) with check (public.is_admin());
create policy reports_admin_write on public.reports for all using (public.is_admin()) with check (public.is_admin());
create policy change_log_admin_write on public.change_log for all using (public.is_admin()) with check (public.is_admin());
create policy search_terms_admin_write on public.search_terms_snapshot for all using (public.is_admin()) with check (public.is_admin());
create policy kpi_admin_write on public.kpi_snapshots for all using (public.is_admin()) with check (public.is_admin());
create policy client_users_admin_write on public.client_users for all using (public.is_admin()) with check (public.is_admin());

-- ----------------------------------------------------------------------------
-- 4. Bootstrap Sharon as the first admin
-- After signing in for the first time via magic link, run:
--
--   insert into public.admin_users (user_id, email)
--   select id, email from auth.users where email = 'sharon@samp.ninja';
--
-- (Done one-time. Future admins added via the portal admin UI.)
-- ----------------------------------------------------------------------------
